version: "3.8"
services:
    Master:
        image: "centos-automation"
        container_name: master
        hostname: ansible_master
        ports: 
            - "22:22"
            - "80:80"
        volumes:
            - /Users/prathang/Prathang/Learnings/Shared:/data

    Target-node-1:
        image: "centos-ssh"
        container_name: target1
        hostname: target-1
        volumes:
            - /Users/prathang/Prathang/Learnings/Shared:/data

    Target-node-2:
        image: "centos-ssh"
        container_name: target2
        hostname: target-2
        volumes:
            - /Users/prathang/Prathang/Learnings/Shared:/data